spring:
  cloud:
    gateway:
      routes:
        - id : customer_service
          uri: lb://customer_service
          predicates:
            - Path=/rest-api/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer_service
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
        - id: payment_service
          uri: lb://payment_service
          predicates:
            - Path=/rest-api/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment_service
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
